// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_scrbooting
void ui_scrbooting_screen_init(void);
void ui_event_scrbooting(lv_event_t * e);
lv_obj_t * ui_scrbooting;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES
lv_obj_t * uic_scrbooting;

// SCREEN: ui_scrmain
void ui_scrmain_screen_init(void);
lv_obj_t * ui_scrmain;
void ui_event_TabView1(lv_event_t * e);
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Tab1;
lv_obj_t * ui_Panel_left;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel79;
lv_obj_t * ui_Label79;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Label84;
lv_obj_t * ui_Panel80;
lv_obj_t * ui_Label192;
lv_obj_t * ui_Label81;
lv_obj_t * ui_Label85;
lv_obj_t * ui_Label86;
lv_obj_t * ui_Label88;
lv_obj_t * ui_Panel84;
lv_obj_t * ui_Panel77;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Panel81;
lv_obj_t * ui_Label190;
lv_obj_t * ui_Label193;
lv_obj_t * ui_Label194;
lv_obj_t * ui_Label196;
lv_obj_t * ui_Panel86;
lv_obj_t * ui_Panel82;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Panel83;
lv_obj_t * ui_Label200;
lv_obj_t * ui_Label195;
lv_obj_t * ui_Label197;
lv_obj_t * ui_Label198;
lv_obj_t * ui_Panel89;
lv_obj_t * ui_Panel85;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Panel87;
lv_obj_t * ui_Label204;
lv_obj_t * ui_Label199;
lv_obj_t * ui_Label201;
lv_obj_t * ui_Label202;
lv_obj_t * ui_Panel92;
lv_obj_t * ui_Panel90;
lv_obj_t * ui_Label206;
lv_obj_t * ui_Label208;
lv_obj_t * ui_Label205;
lv_obj_t * ui_Panel91;
lv_obj_t * ui_Label210;
lv_obj_t * ui_Label203;
lv_obj_t * ui_Label207;
lv_obj_t * ui_Panel_right;
lv_obj_t * ui_title;
lv_obj_t * ui_panelbg1;
lv_obj_t * ui_bg1;
lv_obj_t * ui_dlqon;
lv_obj_t * ui_dlqoff;
lv_obj_t * ui_scoff;
lv_obj_t * ui_scon;
lv_obj_t * ui_panelbg2;
lv_obj_t * ui_bg2;
lv_obj_t * ui_sc2off;
lv_obj_t * ui_sc2on;
lv_obj_t * ui_panelbg3;
lv_obj_t * ui_bg3;
lv_obj_t * ui_sc3off;
lv_obj_t * ui_sc3on;
lv_obj_t * ui_panelbg4;
lv_obj_t * ui_bg4;
lv_obj_t * ui_dlq4off;
lv_obj_t * ui_dlq4on;
lv_obj_t * ui_jdd4off;
lv_obj_t * ui_jdd4on;
lv_obj_t * ui_sc4off;
lv_obj_t * ui_sc4on;
lv_obj_t * ui_panelbg5;
lv_obj_t * ui_bg5;
lv_obj_t * ui_dlq5off;
lv_obj_t * ui_dlq5on;
lv_obj_t * ui_sc5off;
lv_obj_t * ui_sc5on;
lv_obj_t * ui_panelbg6;
lv_obj_t * ui_bg6;
lv_obj_t * ui_sc6off;
lv_obj_t * ui_sc6on;
lv_obj_t * ui_bg_tool;
lv_obj_t * ui_Panel93;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Label209;
lv_obj_t * ui_Panel95;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Label212;
lv_obj_t * ui_Panel96;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Label213;
lv_obj_t * ui_Panel97;
void ui_event_Switch5(lv_event_t * e);
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Label214;
lv_obj_t * ui_Tab2;
void ui_event_TabView6(lv_event_t * e);
lv_obj_t * ui_TabView6;
lv_obj_t * ui_Tab3nav3;
lv_obj_t * ui_Panel71;
lv_obj_t * ui_Panel74;
lv_obj_t * ui_Label135;
lv_obj_t * ui_Label136;
lv_obj_t * ui_Label138;
lv_obj_t * ui_Label140;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_chartKV6;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Tab3nav7;
lv_obj_t * ui_Panel75;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label92;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;
lv_obj_t * ui_chartKV2;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Label56;
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Tab3nav8;
lv_obj_t * ui_Panel98;
lv_obj_t * ui_Panel64;
lv_obj_t * ui_Label189;
lv_obj_t * ui_Label65;
lv_obj_t * ui_Label101;
lv_obj_t * ui_Label181;
lv_obj_t * ui_chartKV3;
lv_obj_t * ui_Panel76;
lv_obj_t * ui_Label182;
lv_obj_t * ui_Label183;
lv_obj_t * ui_Label184;
lv_obj_t * ui_Label185;
lv_obj_t * ui_Label186;
lv_obj_t * ui_Label187;
lv_obj_t * ui_Tab3nav9;
lv_obj_t * ui_Panel101;
lv_obj_t * ui_Panel78;
lv_obj_t * ui_Label222;
lv_obj_t * ui_Label188;
lv_obj_t * ui_Label191;
lv_obj_t * ui_Label211;
lv_obj_t * ui_chartKV7;
lv_obj_t * ui_Panel99;
lv_obj_t * ui_Label215;
lv_obj_t * ui_Label216;
lv_obj_t * ui_Label217;
lv_obj_t * ui_Label218;
lv_obj_t * ui_Label219;
lv_obj_t * ui_Label220;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Panel104;
lv_obj_t * ui_Panel100;
lv_obj_t * ui_Label232;
lv_obj_t * ui_Label221;
lv_obj_t * ui_Label223;
lv_obj_t * ui_Label224;
lv_obj_t * ui_chartKV8;
lv_obj_t * ui_Panel102;
lv_obj_t * ui_Label225;
lv_obj_t * ui_Label226;
lv_obj_t * ui_Label227;
lv_obj_t * ui_Label228;
lv_obj_t * ui_Label229;
lv_obj_t * ui_Label230;
lv_obj_t * ui_Tab3;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage13;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label99;
lv_obj_t * ui_Label103;
lv_obj_t * ui_Label104;
lv_obj_t * ui_Label105;
lv_obj_t * ui_Panel19;
void ui_event_Dropdown3(lv_event_t * e);
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Label102;
void ui_event_pttextarea3(lv_event_t * e);
lv_obj_t * ui_pttextarea3;
void ui_event_Dropdown5(lv_event_t * e);
lv_obj_t * ui_Dropdown5;
void ui_event_pttextarea4(lv_event_t * e);
lv_obj_t * ui_pttextarea4;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label107;
void ui_event_pttextarea6(lv_event_t * e);
lv_obj_t * ui_pttextarea6;
void ui_event_Dropdown4(lv_event_t * e);
lv_obj_t * ui_Dropdown4;
void ui_event_pttextarea1(lv_event_t * e);
lv_obj_t * ui_pttextarea1;
void ui_event_Dropdown7(lv_event_t * e);
lv_obj_t * ui_Dropdown7;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Label108;
void ui_event_pttextarea8(lv_event_t * e);
lv_obj_t * ui_pttextarea8;
void ui_event_Dropdown6(lv_event_t * e);
lv_obj_t * ui_Dropdown6;
void ui_event_pttextarea5(lv_event_t * e);
lv_obj_t * ui_pttextarea5;
lv_obj_t * ui_TabPage17;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label76;
lv_obj_t * ui_Label91;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Label93;
void ui_event_pttextarea18(lv_event_t * e);
lv_obj_t * ui_pttextarea18;
void ui_event_pttextarea13(lv_event_t * e);
lv_obj_t * ui_pttextarea13;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Label106;
void ui_event_pttextarea12(lv_event_t * e);
lv_obj_t * ui_pttextarea12;
void ui_event_pttextarea7(lv_event_t * e);
lv_obj_t * ui_pttextarea7;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Label110;
void ui_event_pttextarea15(lv_event_t * e);
lv_obj_t * ui_pttextarea15;
lv_obj_t * ui_Label111;
lv_obj_t * ui_Dropdown13;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Label114;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_Label112;
void ui_event_pttextarea11(lv_event_t * e);
lv_obj_t * ui_pttextarea11;
void ui_event_pttextarea9(lv_event_t * e);
lv_obj_t * ui_pttextarea9;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label115;
void ui_event_pttextarea16(lv_event_t * e);
lv_obj_t * ui_pttextarea16;
void ui_event_pttextarea10(lv_event_t * e);
lv_obj_t * ui_pttextarea10;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Label117;
void ui_event_pttextarea17(lv_event_t * e);
lv_obj_t * ui_pttextarea17;
lv_obj_t * ui_Label109;
void ui_event_pttextarea19(lv_event_t * e);
lv_obj_t * ui_pttextarea19;
lv_obj_t * ui_TabPage7;
lv_obj_t * ui_Panel40;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Label129;
lv_obj_t * ui_Label116;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Label118;
void ui_event_pttextarea30(lv_event_t * e);
lv_obj_t * ui_pttextarea30;
void ui_event_pttextarea14(lv_event_t * e);
lv_obj_t * ui_pttextarea14;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label119;
void ui_event_pttextarea20(lv_event_t * e);
lv_obj_t * ui_pttextarea20;
void ui_event_pttextarea21(lv_event_t * e);
lv_obj_t * ui_pttextarea21;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Label120;
void ui_event_pttextarea22(lv_event_t * e);
lv_obj_t * ui_pttextarea22;
void ui_event_pttextarea24(lv_event_t * e);
lv_obj_t * ui_pttextarea24;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Label122;
void ui_event_pttextarea26(lv_event_t * e);
lv_obj_t * ui_pttextarea26;
lv_obj_t * ui_Label123;
void ui_event_pttextarea23(lv_event_t * e);
lv_obj_t * ui_pttextarea23;
lv_obj_t * ui_Panel38;
lv_obj_t * ui_Panel39;
lv_obj_t * ui_Label121;
void ui_event_Checkbox3(lv_event_t * e);
lv_obj_t * ui_Checkbox3;
void ui_event_Checkbox5(lv_event_t * e);
lv_obj_t * ui_Checkbox5;
lv_obj_t * ui_TabPage8;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label30;
void ui_event_pttextarea(lv_event_t * e);
lv_obj_t * ui_pttextarea;
void ui_event_cttextarea(lv_event_t * e);
lv_obj_t * ui_cttextarea;
lv_obj_t * ui_TabPage12;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label7;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label4;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label2;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label5;
lv_obj_t * ui_TabPage6;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label14;
void ui_event_TextArea7(lv_event_t * e);
lv_obj_t * ui_TextArea7;
lv_obj_t * ui_Label15;
void ui_event_TextArea9(lv_event_t * e);
lv_obj_t * ui_TextArea9;
void ui_event_TextArea8(lv_event_t * e);
lv_obj_t * ui_TextArea8;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label90;
void ui_event_TextArea16(lv_event_t * e);
lv_obj_t * ui_TextArea16;
lv_obj_t * ui_key8;
lv_obj_t * ui_Label25;
void ui_event_Keyboard10(lv_event_t * e);
lv_obj_t * ui_Keyboard10;
lv_obj_t * ui_TabPage10;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_timems4;
lv_obj_t * ui_Label19;
void ui_event_yeartextarea4(lv_event_t * e);
lv_obj_t * ui_yeartextarea4;
lv_obj_t * ui_Label13;
lv_obj_t * ui_timems3;
lv_obj_t * ui_Label20;
void ui_event_yeartextarea3(lv_event_t * e);
lv_obj_t * ui_yeartextarea3;
lv_obj_t * ui_Label16;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label21;
lv_obj_t * ui_key13;
lv_obj_t * ui_Label95;
void ui_event_Keyboard4(lv_event_t * e);
lv_obj_t * ui_Keyboard4;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_timems12;
lv_obj_t * ui_Label40;
void ui_event_yeartextarea12(lv_event_t * e);
lv_obj_t * ui_yeartextarea12;
lv_obj_t * ui_timems1;
lv_obj_t * ui_Label23;
void ui_event_yeartextarea1(lv_event_t * e);
lv_obj_t * ui_yeartextarea1;
lv_obj_t * ui_timems7;
lv_obj_t * ui_Label24;
void ui_event_yeartextarea7(lv_event_t * e);
lv_obj_t * ui_yeartextarea7;
lv_obj_t * ui_timems8;
lv_obj_t * ui_Label27;
void ui_event_yeartextarea8(lv_event_t * e);
lv_obj_t * ui_yeartextarea8;
lv_obj_t * ui_timems9;
lv_obj_t * ui_Label29;
void ui_event_yeartextarea9(lv_event_t * e);
lv_obj_t * ui_yeartextarea9;
lv_obj_t * ui_timems10;
lv_obj_t * ui_Label32;
void ui_event_yeartextarea10(lv_event_t * e);
lv_obj_t * ui_yeartextarea10;
void ui_event_monthtextarea2(lv_event_t * e);
lv_obj_t * ui_monthtextarea2;
void ui_event_daytextarea2(lv_event_t * e);
lv_obj_t * ui_daytextarea2;
void ui_event_hourtextarea2(lv_event_t * e);
lv_obj_t * ui_hourtextarea2;
void ui_event_mintextarea2(lv_event_t * e);
lv_obj_t * ui_mintextarea2;
void ui_event_secondtextarea2(lv_event_t * e);
lv_obj_t * ui_secondtextarea2;
lv_obj_t * ui_Label33;
lv_obj_t * ui_key2;
lv_obj_t * ui_Label36;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_paddialog;
void ui_event_pttextarea2(lv_event_t * e);
lv_obj_t * ui_pttextarea2;
lv_obj_t * ui_Label89;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_key10;
lv_obj_t * ui_Label179;
void ui_event_Keyboard6(lv_event_t * e);
lv_obj_t * ui_Keyboard6;
lv_obj_t * ui_key6;
lv_obj_t * ui_Label35;
void ui_event_Keyboard8(lv_event_t * e);
lv_obj_t * ui_Keyboard8;
lv_obj_t * ui_Tab4;
void ui_event_TabView3(lv_event_t * e);
lv_obj_t * ui_TabView3;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Panel141;
lv_obj_t * ui_Panel62;
lv_obj_t * ui_Panel63;
lv_obj_t * ui_Label236;
lv_obj_t * ui_Panel65;
lv_obj_t * ui_Label137;
lv_obj_t * ui_Panel66;
lv_obj_t * ui_Label141;
lv_obj_t * ui_Panel142;
lv_obj_t * ui_Label237;
lv_obj_t * ui_Panel67;
lv_obj_t * ui_Label142;
lv_obj_t * ui_Panel107;
lv_obj_t * ui_Panel68;
lv_obj_t * ui_Label153;
lv_obj_t * ui_Panel70;
lv_obj_t * ui_Label143;
lv_obj_t * ui_Panel72;
lv_obj_t * ui_Label145;
lv_obj_t * ui_Panel103;
lv_obj_t * ui_Label146;
lv_obj_t * ui_Panel105;
lv_obj_t * ui_Label147;
lv_obj_t * ui_Panel135;
lv_obj_t * ui_Panel136;
lv_obj_t * ui_Label180;
lv_obj_t * ui_Panel137;
lv_obj_t * ui_Label231;
lv_obj_t * ui_Panel138;
lv_obj_t * ui_Label233;
lv_obj_t * ui_Panel69;
lv_obj_t * ui_Label144;
lv_obj_t * ui_Panel139;
lv_obj_t * ui_Label234;
lv_obj_t * ui_Panel113;
lv_obj_t * ui_Panel106;
lv_obj_t * ui_Label160;
lv_obj_t * ui_Panel108;
lv_obj_t * ui_Label148;
lv_obj_t * ui_Panel109;
lv_obj_t * ui_Label154;
lv_obj_t * ui_Panel110;
lv_obj_t * ui_Label157;
lv_obj_t * ui_Panel111;
lv_obj_t * ui_Label158;
lv_obj_t * ui_Panel119;
lv_obj_t * ui_Panel112;
lv_obj_t * ui_Label165;
lv_obj_t * ui_Panel114;
lv_obj_t * ui_Label159;
lv_obj_t * ui_Panel115;
lv_obj_t * ui_Label161;
lv_obj_t * ui_Panel116;
lv_obj_t * ui_Label162;
lv_obj_t * ui_Panel117;
lv_obj_t * ui_Label163;
lv_obj_t * ui_Panel125;
lv_obj_t * ui_Panel118;
lv_obj_t * ui_Label170;
lv_obj_t * ui_Panel120;
lv_obj_t * ui_Label164;
lv_obj_t * ui_Panel121;
lv_obj_t * ui_Label166;
lv_obj_t * ui_Panel122;
lv_obj_t * ui_Label167;
lv_obj_t * ui_Panel123;
lv_obj_t * ui_Label168;
lv_obj_t * ui_Panel131;
lv_obj_t * ui_Panel124;
lv_obj_t * ui_Label176;
lv_obj_t * ui_Panel126;
lv_obj_t * ui_Label169;
lv_obj_t * ui_Panel127;
lv_obj_t * ui_Label171;
lv_obj_t * ui_Panel128;
lv_obj_t * ui_Label172;
lv_obj_t * ui_Panel129;
lv_obj_t * ui_Label173;
lv_obj_t * ui_Panel144;
lv_obj_t * ui_Panel130;
lv_obj_t * ui_Label240;
lv_obj_t * ui_Panel132;
lv_obj_t * ui_Label174;
lv_obj_t * ui_Panel133;
lv_obj_t * ui_Label177;
lv_obj_t * ui_Panel134;
lv_obj_t * ui_Label235;
lv_obj_t * ui_Panel140;
lv_obj_t * ui_Label238;
lv_obj_t * ui_Panel150;
lv_obj_t * ui_Panel143;
lv_obj_t * ui_Label245;
lv_obj_t * ui_Panel145;
lv_obj_t * ui_Label239;
lv_obj_t * ui_Panel146;
lv_obj_t * ui_Label241;
lv_obj_t * ui_Panel147;
lv_obj_t * ui_Label242;
lv_obj_t * ui_Panel148;
lv_obj_t * ui_Label243;
lv_obj_t * ui_Panel156;
lv_obj_t * ui_Panel149;
lv_obj_t * ui_Label250;
lv_obj_t * ui_Panel151;
lv_obj_t * ui_Label244;
lv_obj_t * ui_Panel152;
lv_obj_t * ui_Label246;
lv_obj_t * ui_Panel153;
lv_obj_t * ui_Label247;
lv_obj_t * ui_Panel154;
lv_obj_t * ui_Label248;
lv_obj_t * ui_Panel162;
lv_obj_t * ui_Panel155;
lv_obj_t * ui_Label255;
lv_obj_t * ui_Panel157;
lv_obj_t * ui_Label249;
lv_obj_t * ui_Panel158;
lv_obj_t * ui_Label251;
lv_obj_t * ui_Panel159;
lv_obj_t * ui_Label252;
lv_obj_t * ui_Panel160;
lv_obj_t * ui_Label253;
lv_obj_t * ui_Tab5;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label98;
lv_obj_t * ui_Label100;
lv_obj_t * ui_Tab6;
lv_obj_t * ui_Panel208;
lv_obj_t * ui_Panel161;
lv_obj_t * ui_Panel163;
lv_obj_t * ui_Label285;
lv_obj_t * ui_Panel164;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Panel166;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Panel167;
lv_obj_t * ui_Panel169;
lv_obj_t * ui_Label96;
lv_obj_t * ui_Panel168;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Panel172;
lv_obj_t * ui_Label113;
lv_obj_t * ui_Panel165;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Panel171;
lv_obj_t * ui_Label254;
lv_obj_t * ui_Panel178;
lv_obj_t * ui_Panel170;
lv_obj_t * ui_Label259;
lv_obj_t * ui_Panel173;
lv_obj_t * ui_Label97;
lv_obj_t * ui_Panel174;
lv_obj_t * ui_Label155;
lv_obj_t * ui_Panel175;
lv_obj_t * ui_Label256;
lv_obj_t * ui_Panel176;
lv_obj_t * ui_Label257;
lv_obj_t * ui_Panel184;
lv_obj_t * ui_Panel177;
lv_obj_t * ui_Label264;
lv_obj_t * ui_Panel179;
lv_obj_t * ui_Label258;
lv_obj_t * ui_Panel180;
lv_obj_t * ui_Label260;
lv_obj_t * ui_Panel181;
lv_obj_t * ui_Label261;
lv_obj_t * ui_Panel182;
lv_obj_t * ui_Label262;
lv_obj_t * ui_Panel190;
lv_obj_t * ui_Panel183;
lv_obj_t * ui_Label269;
lv_obj_t * ui_Panel185;
lv_obj_t * ui_Label263;
lv_obj_t * ui_Panel186;
lv_obj_t * ui_Label265;
lv_obj_t * ui_Panel187;
lv_obj_t * ui_Label266;
lv_obj_t * ui_Panel188;
lv_obj_t * ui_Label267;
lv_obj_t * ui_Panel196;
lv_obj_t * ui_Panel189;
lv_obj_t * ui_Label274;
lv_obj_t * ui_Panel191;
lv_obj_t * ui_Label268;
lv_obj_t * ui_Panel192;
lv_obj_t * ui_Label270;
lv_obj_t * ui_Panel193;
lv_obj_t * ui_Label271;
lv_obj_t * ui_Panel194;
lv_obj_t * ui_Label272;
lv_obj_t * ui_Panel202;
lv_obj_t * ui_Panel195;
lv_obj_t * ui_Label279;
lv_obj_t * ui_Panel197;
lv_obj_t * ui_Label273;
lv_obj_t * ui_Panel198;
lv_obj_t * ui_Label275;
lv_obj_t * ui_Panel199;
lv_obj_t * ui_Label276;
lv_obj_t * ui_Panel200;
lv_obj_t * ui_Label277;
lv_obj_t * ui_Panel209;
lv_obj_t * ui_Panel201;
lv_obj_t * ui_Label284;
lv_obj_t * ui_Panel203;
lv_obj_t * ui_Label278;
lv_obj_t * ui_Panel204;
lv_obj_t * ui_Label280;
lv_obj_t * ui_Panel205;
lv_obj_t * ui_Label281;
lv_obj_t * ui_Panel206;
lv_obj_t * ui_Label282;
lv_obj_t * ui_tool;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label156;
lv_obj_t * ui_dialog;
lv_obj_t * ui_Label152;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label60;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label139;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label39;
lv_obj_t * ui_time;
lv_obj_t * ui_Label87;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrbooting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_scrmain, LV_SCR_LOAD_ANIM_FADE_ON, 400, 800, &ui_scrmain_screen_init);
    }
}

void ui_event_TabView1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        maintablechanged(e);
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        selftestvaluechanged(e);
    }
}

void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lightvaluechanged(e);
    }
}

void ui_event_TabView6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        histtablechanged(e);
    }
}

void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        chutouvaluechanged(e);
    }
}

void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        settingstablechanged(e);
    }
}

void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        positionAchanged(e);
    }
}

void ui_event_pttextarea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea3);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  183);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        tempAdefocused(e);
    }
}

void ui_event_Dropdown5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        typeAchanged(e);
    }
}

void ui_event_pttextarea4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea4);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  30);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        idAdefocused(e);
    }
}

void ui_event_pttextarea6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea6);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  183);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        tempBdefocused(e);
    }
}

void ui_event_Dropdown4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        typeBchanged(e);
    }
}

void ui_event_pttextarea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea1);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  30);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        idBdefocused(e);
    }
}

void ui_event_Dropdown7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        positionBchanged(e);
    }
}

void ui_event_pttextarea8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea8);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  183);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        tempCdefocused(e);
    }
}

void ui_event_Dropdown6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        typeCchanged(e);
    }
}

void ui_event_pttextarea5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea5);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  30);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        idCdefocused(e);
    }
}

void ui_event_pttextarea18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea18);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea13);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea12);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea7);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea15);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea11);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea9);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea16);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea10);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea17);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea19);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea30);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea14);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea20);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea21);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea22);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea24);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea26);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_pttextarea23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea23);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  10);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Checkbox3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Checkbox5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        connecttypechanged(e);
    }
}

void ui_event_Checkbox5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Checkbox3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        connecttypechanged(e);
    }
}

void ui_event_pttextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_cttextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_cttextarea);
        _ui_basic_set_property(ui_key6, _UI_BASIC_PROPERTY_POSITION_X,  200);
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_key6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        preparecalcclicked(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        voltagecalcclicked(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        currentcalcclicked(e);
    }
}

void ui_event_TextArea7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_TextArea7);
    }
}

void ui_event_TextArea9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_TextArea9);
    }
}

void ui_event_TextArea8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_TextArea8);
    }
}

void ui_event_TextArea16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_TextArea16);
    }
}

void ui_event_Keyboard10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_yeartextarea4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_yeartextarea4);
    }
}

void ui_event_yeartextarea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_yeartextarea3);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touchscreencalc(e);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_yeartextarea12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea12);
    }
}

void ui_event_yeartextarea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea1);
    }
}

void ui_event_yeartextarea7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea7);
    }
}

void ui_event_yeartextarea8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea8);
    }
}

void ui_event_yeartextarea9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea9);
    }
}

void ui_event_yeartextarea10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_yeartextarea10);
    }
}

void ui_event_monthtextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_monthtextarea2);
    }
}

void ui_event_daytextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_daytextarea2);
    }
}

void ui_event_hourtextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_hourtextarea2);
    }
}

void ui_event_mintextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_mintextarea2);
    }
}

void ui_event_secondtextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_secondtextarea2);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_pttextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard6,  ui_pttextarea2);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        checkpassword(e);
    }
}

void ui_event_Keyboard6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_Keyboard8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_TabView3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        celldatatablechanged(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clearlogclicked(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_dialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aclosebtnclicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_img_230_png_load();
    ui_img_a_png_load();
    ui_img_b_png_load();
    ui_img_c_png_load();
    ui_img_wifi_png_load();
    ui_img_bg1_png_load();
    ui_img_dlq_on_png_load();
    ui_img_dlq_off_png_load();
    ui_img_sc_off_png_load();
    ui_img_sc_on_png_load();
    ui_img_bg2_png_load();
    ui_img_sc2off_png_load();
    ui_img_sc2on_png_load();
    ui_img_bg3_png_load();
    ui_img_sc3off_png_load();
    ui_img_sc3on_png_load();
    ui_img_bg4_png_load();
    ui_img_dlq4off_png_load();
    ui_img_dlq4on_png_load();
    ui_img_jdd4off_png_load();
    ui_img_jdd4on_png_load();
    ui_img_sc4off_png_load();
    ui_img_sc4on_png_load();
    ui_img_bg5_png_load();
    ui_img_dlq5off_png_load();
    ui_img_dlq5on_png_load();
    ui_img_sc5off_png_load();
    ui_img_sc5on_png_load();
    ui_img_bg6_png_load();
    ui_img_sc6off_png_load();
    ui_img_sc6on_png_load();
    ui_img_no_png_load();
    ui_img_ok_png_load();
    ui_scrbooting_screen_init();
    ui_scrmain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrbooting);
}
