// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "ui.h"

void ta_event_cb(lv_event_t * e)
{
	// Your code here
}

void aclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void checkpassword(lv_event_t * e)
{
	// Your code here
}

void selftestvaluechanged(lv_event_t * e)
{
	// Your code here
}

void lightvaluechanged(lv_event_t * e)
{
	// Your code here
}

void histtablechanged(lv_event_t * e)
{
	// Your code here
}

void chutouvaluechanged(lv_event_t * e)
{
	// Your code here
}

void preparecalcclicked(lv_event_t * e)
{
	// Your code here
}

void voltagecalcclicked(lv_event_t * e)
{
	// Your code here
}

void currentcalcclicked(lv_event_t * e)
{
	// Your code here
}

void touchscreencalc(lv_event_t * e)
{
	// Your code here
}

void celldatatablechanged(lv_event_t * e)
{
	// Your code here
}

void clearlogclicked(lv_event_t * e)
{
	// Your code here
}

void positionAchanged(lv_event_t * e)
{
	// Your code here
}

void typeAchanged(lv_event_t * e)
{
	// Your code here
}

void typeBchanged(lv_event_t * e)
{
	// Your code here
}

void positionBchanged(lv_event_t * e)
{
	// Your code here
}

void typeCchanged(lv_event_t * e)
{
	// Your code here
}

void connecttypechanged(lv_event_t * e)
{
	// Your code here
}

void settingstablechanged(lv_event_t * e)
{
	// Your code here
}

void maintablechanged(lv_event_t * e)
{
	// Your code here
}

void tempAdefocused(lv_event_t * e)
{
	// Your code here
}

void idAdefocused(lv_event_t * e)
{
	// Your code here
}

void tempBdefocused(lv_event_t * e)
{
	// Your code here
}

void idBdefocused(lv_event_t * e)
{
	// Your code here
}

void tempCdefocused(lv_event_t * e)
{
	// Your code here
}

void idCdefocused(lv_event_t * e)
{
	// Your code here
}
