// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void maintablechanged(lv_event_t * e);
void selftestvaluechanged(lv_event_t * e);
void lightvaluechanged(lv_event_t * e);
void histtablechanged(lv_event_t * e);
void chutouvaluechanged(lv_event_t * e);
void settingstablechanged(lv_event_t * e);
void positionAchanged(lv_event_t * e);
void tempAdefocused(lv_event_t * e);
void typeAchanged(lv_event_t * e);
void idAdefocused(lv_event_t * e);
void tempBdefocused(lv_event_t * e);
void typeBchanged(lv_event_t * e);
void idBdefocused(lv_event_t * e);
void positionBchanged(lv_event_t * e);
void tempCdefocused(lv_event_t * e);
void typeCchanged(lv_event_t * e);
void idCdefocused(lv_event_t * e);
void connecttypechanged(lv_event_t * e);
void preparecalcclicked(lv_event_t * e);
void voltagecalcclicked(lv_event_t * e);
void currentcalcclicked(lv_event_t * e);
void ta_event_cb(lv_event_t * e);
void touchscreencalc(lv_event_t * e);
void checkpassword(lv_event_t * e);
void celldatatablechanged(lv_event_t * e);
void clearlogclicked(lv_event_t * e);
void aclosebtnclicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
