// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_text1[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_text1[1] = {255};

const ui_theme_variable_t _ui_theme_color_but1[1] = {0x354355};
const ui_theme_variable_t _ui_theme_alpha_but1[1] = {255};

const ui_theme_variable_t _ui_theme_color_but2[1] = {0x929BA5};
const ui_theme_variable_t _ui_theme_alpha_but2[1] = {255};

const ui_theme_variable_t _ui_theme_color_red[1] = {0xFF0000};
const ui_theme_variable_t _ui_theme_alpha_red[1] = {255};

const ui_theme_variable_t _ui_theme_color_green[1] = {0x06FB20};
const ui_theme_variable_t _ui_theme_alpha_green[1] = {255};

const ui_theme_variable_t _ui_theme_color_primary[1] = {0xEE5500};
const ui_theme_variable_t _ui_theme_alpha_primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_bgPrimary[1] = {0x292831};
const ui_theme_variable_t _ui_theme_alpha_bgPrimary[1] = {255};

const ui_theme_variable_t _ui_theme_color_bg2[1] = {0x526D94};
const ui_theme_variable_t _ui_theme_alpha_bg2[1] = {255};

const ui_theme_variable_t _ui_theme_color_yellow[1] = {0xF4EA2A};
const ui_theme_variable_t _ui_theme_alpha_yellow[1] = {255};

const ui_theme_variable_t _ui_theme_color_primar22[1] = {0x05F6F7};
const ui_theme_variable_t _ui_theme_alpha_primar22[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

