// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_TEXT1 0
#define UI_THEME_COLOR_BUT1 1
#define UI_THEME_COLOR_BUT2 2
#define UI_THEME_COLOR_RED 3
#define UI_THEME_COLOR_GREEN 4
#define UI_THEME_COLOR_PRIMARY 5
#define UI_THEME_COLOR_BGPRIMARY 6
#define UI_THEME_COLOR_BG2 7
#define UI_THEME_COLOR_YELLOW 8
#define UI_THEME_COLOR_PRIMAR22 9

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_text1[1];
extern const ui_theme_variable_t _ui_theme_alpha_text1[1];

extern const ui_theme_variable_t _ui_theme_color_but1[1];
extern const ui_theme_variable_t _ui_theme_alpha_but1[1];

extern const ui_theme_variable_t _ui_theme_color_but2[1];
extern const ui_theme_variable_t _ui_theme_alpha_but2[1];

extern const ui_theme_variable_t _ui_theme_color_red[1];
extern const ui_theme_variable_t _ui_theme_alpha_red[1];

extern const ui_theme_variable_t _ui_theme_color_green[1];
extern const ui_theme_variable_t _ui_theme_alpha_green[1];

extern const ui_theme_variable_t _ui_theme_color_primary[1];
extern const ui_theme_variable_t _ui_theme_alpha_primary[1];

extern const ui_theme_variable_t _ui_theme_color_bgPrimary[1];
extern const ui_theme_variable_t _ui_theme_alpha_bgPrimary[1];

extern const ui_theme_variable_t _ui_theme_color_bg2[1];
extern const ui_theme_variable_t _ui_theme_alpha_bg2[1];

extern const ui_theme_variable_t _ui_theme_color_yellow[1];
extern const ui_theme_variable_t _ui_theme_alpha_yellow[1];

extern const ui_theme_variable_t _ui_theme_color_primar22[1];
extern const ui_theme_variable_t _ui_theme_alpha_primar22[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
