// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "../ui.h"


// IMAGE DATA: assets/bg2.png
lv_img_dsc_t ui_img_bg2_png = {
    .header.always_zero = 0,
    .header.w = 210,
    .header.h = 350,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_bg2_png_load()
{
    ui_img_bg2_png.data = UI_LOAD_IMAGE("S:assets/ui_img_bg2_png.bin", 8303, 147000);
    ui_img_bg2_png.data_size = 147000;
}
