// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "../ui.h"


// IMAGE DATA: assets/A.png
lv_img_dsc_t ui_img_a_png = {
    .header.always_zero = 0,
    .header.w = 16,
    .header.h = 16,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_a_png_load()
{
    ui_img_a_png.data = UI_LOAD_IMAGE("S:assets/ui_img_a_png.bin", 359, 768);
    ui_img_a_png.data_size = 768;
}
