// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric700

#include "../ui.h"


// IMAGE DATA: assets/sc2off.png
lv_img_dsc_t ui_img_sc2off_png = {
    .header.always_zero = 0,
    .header.w = 210,
    .header.h = 350,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_sc2off_png_load()
{
    ui_img_sc2off_png.data = UI_LOAD_IMAGE("S:assets/ui_img_sc2off_png.bin", 941, 220500);
    ui_img_sc2off_png.data_size = 220500;
}
